recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Root URL configuration for Django project
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

# Add media URL mapping
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home
from .views import RecipeListView
from . import views


app_name = 'recipes'

urlpatterns = [
    path('', views.login_view, name='login'),  # Set login view as the default page
    path('home/', home, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('login/', views.login_view, name='login'),
    path('breakfasts/', views.breakfasts_view, name='breakfasts'),  # Add URL for breakfasts
    path('lunches/', views.lunches_view, name='lunches'),  # Add URL for lunches
    path('dinners/', views.dinners_view, name='dinners'),  # Add URL for dinners
    path('search/', views.search_view, name='search'),
    path('add-recipe/', views.add_recipe, name='add-recipe'),
    path('about-me/', views.about_me, name='about-me'),

]

recipes/models.py
from django.db import models

class Recipe(models.Model):
    TYPE_CHOICES = (
        ('Breakfast', 'Breakfasts'),
        ('Lunch', 'Lunches'),
        ('Dinner', 'Dinners'),
    )

    id = models.AutoField(primary_key=True)
    recipe_name = models.CharField(max_length=255)
    ingredients = models.TextField()
    cooking_time = models.CharField(max_length=10)
    difficulty = models.CharField(max_length=50)
    pic = models.ImageField(upload_to='media/media', null=True, blank=True)
    recipe_type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='Breakfast')


    def __str__(self):
        return self.recipe_name

recipes/forms.py
from django import forms
from .models import Recipe

CHART_CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

DIFFICULTY_CHOICES = (
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('hard', 'Hard')
)

class RecipeSearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    recipe_name = forms.CharField(label='Recipe Name', max_length=100)
    ingredients = forms.CharField(label='Ingredients', max_length=200)
    cooking_time = forms.IntegerField(label='Cooking Time (minutes)')
    difficulty = forms.ChoiceField(label='Difficulty', choices=DIFFICULTY_CHOICES)
    chart_type = forms.ChoiceField(label='Chart Type', choices=CHART_CHOICES)

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_name', 'ingredients', 'difficulty', 'cooking_time', 'recipe_type', 'pic']

recipes/views.py
from django.shortcuts import render
from .models import Recipe
from django.views.generic import ListView
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.db.models import Q
from .utils import get_chart
from .forms import RecipeSearchForm
import pandas as pd
from .forms import RecipeForm

# Create your views here.

def home(request):
    return render(request, 'recipes/recipes-home.html')

class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipes/recipes-list.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        queryset = super().get_queryset()
        recipe_type = self.request.GET.get('type')
        if recipe_type:
            queryset = queryset.filter(recipe_type=recipe_type)
        return queryset


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('recipes:home')
        else:
            error_message = 'Invalid username or password'
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request, 'login.html')


def breakfasts_view(request):
    # Retrieve breakfast recipes from the database
    breakfast_recipes = Recipe.objects.filter(recipe_type='Breakfast')

    # Pass breakfast recipes to the template context
    context = {'breakfast_recipes': breakfast_recipes}

    return render(request, 'breakfasts.html', context)


def lunches_view(request):
    lunch_recipes = Recipe.objects.filter(recipe_type='Lunch')
    context = {'lunch_recipes': lunch_recipes}
    return render(request, 'lunches.html', context)


def dinners_view(request):
    dinner_recipes = Recipe.objects.filter(recipe_type='Dinner')
    context = {'dinner_recipes': dinner_recipes}
    return render(request, 'dinners.html', context)


def search_view(request):
    if request.method == 'GET':
        query = request.GET.get('query')

        # Perform the search based on the provided query
        search_results = Recipe.objects.filter(
            Q(recipe_name__icontains=query) |
            Q(ingredients__icontains=query) |
            Q(cooking_time__icontains=query) |
            Q(recipe_type__icontains=query)
        )

        # Prepare data for the chart
        chart_type = '#1'  # Replace with the desired chart type
        data = {
            'name': [recipe.recipe_name for recipe in search_results],
            'difficulty': [recipe.difficulty for recipe in search_results],
        }
        chart_data = get_chart(chart_type, data)

        context = {'search_results': search_results, 'query': query, 'chart_data': chart_data}
        return render(request, 'recipes/search.html', context)

    form = RecipeSearchForm()
    context = {'form': form}
    return render(request, 'recipes/search.html', context)


def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.save()
            return redirect('recipes:list')
    else:
        form = RecipeForm()

    return render(request, 'add-recipe.html', {'form': form})


def about_me(request):
    return render(request, 'about-me.html')

recipes/templates/about-me.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>About</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Abel&display=swap"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Abel&display=swap');
      /* Example styles for the columns */
      body {
        font-family: 'Abel', sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 0;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: url("{% static '../static/home-background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
      }

      /* Styles for the hamburger menu icon */
      .icon {
        display: none;
        color: #f2f2f2;
        float: left;
        font-size: 24px;
        padding: 10px 16px;
        cursor: pointer;
        min-width: 30px;
      }

      /* Existing styles for the top navigation bar */
      .topnav {
        overflow: hidden;
        background-color: #333;
      }

      .topnav a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
        font-family: 'Abel', sans-serif;
      }

      .topnav a:hover {
        background-color: #ddd;
        color: black;
      }

      .topnav .icon {
        display: none;
      }
      /* Add animation to the responsive topnav */
      .topnav.responsive {
        position: relative;
        animation: slideDown 0.5s ease forwards;
      }

      /* Add animation to close the responsive topnav */
      .topnav.closing {
        animation: slideUp 0.5s ease forwards;
      }

      /* Define the slideDown animation */
      @keyframes slideDown {
        0% {
          top: -100px; /* Start from above the screen */
        }
        100% {
          top: 0; /* End at the top of the screen */
        }
      }

      /* Media query for screens with a maximum width of 600px */
      @media screen and (max-width: 650px) {
        .topnav:not(.responsive) a:not(.icon) {
          display: none;
        }
        .topnav:not(.responsive) .icon {
          float: left;
          display: block;
          margin-left: 16px; /* Add margin to push it to the top left */
        }

        .topnav.responsive {
          position: relative;
        }

        .topnav.responsive .icon {
          position: absolute;
          left: 10px; /* Adjust the left position as needed */
          top: 0;
          width: 40px; /* Set a fixed width */
        }

        .topnav.responsive a {
          float: none;
          display: block;
          text-align: center; /* Center the text horizontally */
          padding: 14px 0; /* Add padding to center the text vertically */
        }
      }

      /* Styles for the search form */
      .search-form {
        float: right;
        margin-top: 14px;
        margin-right: 16px;
      }

      .search-form input[type='text'] {
        padding: 6px;
        border: none;
        border-radius: 4px;
      }

      .search-form input[type='submit'] {
        padding: 6px 10px;
        background-color: #4caf50;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
      }

      /* Responsive design for screens up to 520px */
      @media (max-width: 520px) {
        .column {
          width: 100%; /* Display 1 recipe per row on smaller screens */
        }
      }

      /* Responsive design for screens from 521px to 782px */
      @media (min-width: 521px) and (max-width: 782px) {
        .column {
          width: 50%; /* Display 2 recipes per row on screens from 521px to 782px */
        }
      }

      /* Responsive design for screens from 783px to 2000px */
      @media (min-width: 783px) and (max-width: 2000px) {
        .column {
          width: 33.33%; /* Display 3 recipes per row on screens from 783px to 2000px */
        }
      }

      /* Responsive design for screens larger than 2000px */
      @media (min-width: 2001px) {
        .column {
          width: 25%; /* Display 4 recipes per row on screens larger than 2000px */
        }
      }

      /* Center the container and add margin at the top */
      .container {
        max-width: 800px;
        margin: 20px auto; /* Center the container horizontally and add margin at the top */
        padding: 20px;
        background-color: #ffe4b5;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        text-align: center;
      }
      /* Button styles */
      .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #4caf50;
        color: white;
        text-decoration: none;
        border-radius: 4px;
        margin: 10px;
      }
    </style>
    <nav class="topnav" id="myTopnav">
      <a href="{% url 'recipes:home' %}">Home</a>
      <a href="{% url 'recipes:list' %}">Recipes</a>
      <a href="{% url 'recipes:add-recipe' %}">Add Recipe</a>
      <a href="{% url 'recipes:about-me' %}">About</a>
      <a href="{% url 'recipes:login' %}">Logout</a>
      <form
        action="{% url 'recipes:search' %}"
        method="GET"
        class="search-form"
        id="search-form"
      >
        {% csrf_token %}
        <input
          type="text"
          name="query"
          placeholder="Search recipe"
          value="{{ query }}"
        />
        <button type="submit">Search</button>
      </form>

      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        &#9776;
      </a>
    </nav>

    <!-- Content of the About Me page -->
    <div class="container">
      <h1>RecipeHub - Where Flavor Meets Simplicity</h1>
      <p>
        RecipeHub is a delightful recipe collection application developed using
        Django and Python, and it's hosted on Heroku. Time to start your
        culinary journey!
      </p>
      <h3>A Personal Note from Reman:</h3>
      <p>
        For me, there's nothing quite like the thrill of taking software and
        making it perform better, look more elegant, and run like a dream. I'm
        genuinely excited about the opportunity to be a part of your team and
        can't wait to collaborate and bring my expertise to the table.
        <br /><br />
        <a href="https://remanbalakdev.com/" target="_blank" class="button"
          >Portfolio</a
        >
        <a
          href="https://www.linkedin.com/in/remanbalak/"
          target="_blank"
          class="button"
          >LinkedIn</a
        >
      </p>
    </div>

    <script>
      // Function to toggle the visibility of navigation links
      function myFunction() {
        var x = document.getElementById('myTopnav');
        if (x.className === 'topnav') {
          x.className += ' responsive';
        } else {
          x.className = 'topnav closing'; // Add the 'closing' class to trigger the closing animation
        }
      }

      // JavaScript to toggle the responsive class and trigger the animation
      function myFunction() {
        var x = document.getElementById('myTopnav');
        var searchBar = document.getElementById('search-form');

        if (x.className === 'topnav') {
          x.className += ' responsive';
          searchBar.style.display = 'none'; // Hide the search bar
        } else {
          x.className = 'topnav';
          searchBar.style.display = 'block'; // Show the search bar
        }
      }
    </script>
  </body>
</html>

recipes/templates/add-recipe.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Add Recipe</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Abel&display=swap"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Abel&display=swap');
      /* Example styles for the columns */
      body {
        font-family: 'Abel', sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 0;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: url("{% static '../static/home-background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
      }
      /* Styles for the columns */
      .column {
        float: left;
        width: 33.33%;
        padding: 10px;
        box-sizing: border-box;
      }
      .container {
        max-width: 800px;
        padding: 20px;
        background-color: #ffe4b5;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        margin-top: 50px;
        display: flex;
        flex-direction: column;
        align-items: center;
      }

      .form-group {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 15px;
      }

      .form-group label {
        flex: 1;
        text-align: left;
      }

      .form-control {
        flex: 2;
        margin-left: 10px;
      }

      /* Clear floats after the columns */
      .row::after {
        content: '';
        clear: both;
        display: table;
      }
      /* Styles for the images */
      img {
        width: 100%;
        height: 1080px; /* adjust this to your desired size */
        object-fit: cover; /* ensures the image covers the entire space */
        transition: all 0.3s ease;
        cursor: pointer;
      }
      /* Styles for the hover effect */
      img:hover {
        transform: scale(1.05);
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
      }
      h2 {
        font-family: 'Abel', sans-serif; /* Change to desired font family */
        font-size: 36px; /* Change to desired font size */
        text-align: left;
        margin-bottom: 20px;
      }
      /* Styles for the hamburger menu icon */
      .icon {
        display: none;
        color: #f2f2f2;
        float: left;
        font-size: 24px;
        padding: 14px 16px;
        cursor: pointer;
      }

      /* Existing styles for the top navigation bar */
      .topnav {
        overflow: hidden;
        background-color: #333;
        z-index: 1000;
      }

      .topnav a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
        font-family: 'Abel', sans-serif;
      }

      .topnav a:hover {
        background-color: #ddd;
        color: black;
      }

      .topnav .icon {
        display: none;
      }
      /* Add animation to the responsive topnav */
      .topnav.responsive {
        position: relative;
        animation: slideDown 0.5s ease forwards;
      }

      /* Add animation to close the responsive topnav */
      .topnav.closing {
        animation: slideUp 0.5s ease forwards;
      }

      /* Define the slideDown animation */
      @keyframes slideDown {
        0% {
          top: -100px; /* Start from above the screen */
        }
        100% {
          top: 0; /* End at the top of the screen */
        }
      }

      /* Media query for screens with a maximum width of 600px */
      @media screen and (max-width: 650px) {
        .topnav:not(.responsive) a:not(.icon) {
          display: none;
        }
        .topnav:not(.responsive) .icon {
          float: left;
          display: block;
          margin-left: 16px; /* Add margin to push it to the top left */
        }

        .topnav.responsive {
          position: relative;
        }

        .topnav.responsive .icon {
          position: absolute;
          left: 10px; /* Adjust the left position as needed */
          top: 0;
          width: 40px;
        }

        .topnav.responsive a {
          float: none;
          display: block;
          text-align: center; /* Center the text horizontally */
          padding: 14px 0; /* Add padding to center the text vertically */
        }
      }

      /* Styles for the search form */
      .search-form {
        float: right;
        margin-top: 14px;
        margin-right: 16px;
      }

      .search-form input[type='text'] {
        padding: 6px;
        border: none;
        border-radius: 4px;
      }

      .search-form input[type='submit'] {
        padding: 6px 10px;
        background-color: #4caf50;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <!-- Navigation bar -->
    <nav class="topnav" id="myTopnav">
      <a href="{% url 'recipes:home' %}">Home</a>
      <a href="{% url 'recipes:list' %}">Recipes</a>
      <a href="{% url 'recipes:add-recipe' %}">Add Recipe</a>
      <a href="{% url 'recipes:about-me' %}">About</a>
      <a href="{% url 'recipes:login' %}">Logout</a>
      <form
        action="{% url 'recipes:search' %}"
        method="GET"
        class="search-form"
        id="search-form"
      >
        {% csrf_token %}
        <input
          type="text"
          name="query"
          placeholder="Search recipe"
          value="{{ query }}"
        />
        <button type="submit">Search</button>
      </form>

      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        &#9776;
      </a>
    </nav>
    <div class="container">
      <h2>Add Recipe</h2>
      <form
        method="POST"
        action="{% url 'recipes:add-recipe' %}"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="form-group">
          <label for="recipeName">Recipe Name</label>
          <input
            type="text"
            class="form-control"
            id="recipeName"
            name="recipe_name"
            required
          />
        </div>
        <div class="form-group">
          <label for="ingredients">Ingredients</label>
          <textarea
            class="form-control"
            id="ingredients"
            name="ingredients"
            required
          ></textarea>
        </div>
        <div class="form-group">
          <label for="cookingTime">Cooking Time (minutes)</label>
          <input
            type="number"
            class="form-control"
            id="cookingTime"
            name="cooking_time"
            required
          />
        </div>
        <div class="form-group">
          <label for="difficulty">Difficulty</label>
          <select
            class="form-control"
            id="difficulty"
            name="difficulty"
            required
          >
            <option value="Easy">Easy</option>
            <option value="Medium">Medium</option>
            <option value="Hard">Hard</option>
          </select>
        </div>
        <div class="form-group">
          <label for="recipeType">Recipe Type</label>
          <select
            class="form-control"
            id="recipeType"
            name="recipe_type"
            required
          >
            <option value="Breakfast">Breakfast</option>
            <option value="Lunch">Lunch</option>
            <option value="Dinner">Dinner</option>
          </select>
        </div>
        <div class="form-group">
          <label for="image">Image</label>
          <input
            type="file"
            class="form-control"
            id="image"
            name="pic"
            accept="image/*"
            required
          />
        </div>
        <!-- Add more form fields for other recipe details -->
        <button
          type="submit"
          class="btn btn-primary"
          style="background-color: #177b17"
        >
          Save
        </button>
        <a href="{% url 'recipes:home' %}" class="btn btn-secondary">Cancel</a>
      </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
      // Function to toggle the visibility of navigation links
      function myFunction() {
        var x = document.getElementById('myTopnav');
        if (x.className === 'topnav') {
          x.className += ' responsive';
        } else {
          x.className = 'topnav closing'; // Add the 'closing' class to trigger the closing animation
        }
      }

      // JavaScript to toggle the responsive class and trigger the animation
      function myFunction() {
        var x = document.getElementById('myTopnav');
        var searchBar = document.getElementById('search-form');

        if (x.className === 'topnav') {
          x.className += ' responsive';
          searchBar.style.display = 'none'; // Hide the search bar
        } else {
          x.className = 'topnav';
          searchBar.style.display = 'block'; // Show the search bar
        }
      }
    </script>
  </body>
</html>

recipes/templates/recipes/recipes-home.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeHub</title>
    <link
      href="https://fonts.googleapis.com/css2?family=Abel&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static '../images/background-image.jpg' %}"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Abel&display=swap');
      body {
        font-family: 'Abel', sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 0;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: url("{% static '../static/home-background.jpg' %}")
          no-repeat fixed;
        background-size: cover;
      }
      /* Styles for the columns */
      .column {
        float: left;
        width: 33.33%;
        padding: 10px;
        box-sizing: border-box;
      }
      .row {
        background-color: #ffe4b5;
        margin-top: 20px;
      }
      /* Clear floats after the columns */
      .row::after {
        content: '';
        clear: both;
        display: table;
      }
      /* Styles for the images */
      img {
        width: 100%;
        height: 280px; /* adjust this to your desired size */
        object-fit: cover; /* ensures the image covers the entire space */
        transition: all 0.3s ease;
        cursor: pointer;
      }
      /* Styles for the hover effect */
      img:hover {
        transform: scale(1.05);
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
      }
      h2 {
        font-family: 'Abel', sans-serif;
        font-size: 24px;
        margin-bottom: 20px;
        text-align: center;
      }
      /* Styles for the hamburger menu icon */
      .icon {
        display: none;
        color: #f2f2f2;
        float: left;
        font-size: 24px;
        padding: 14px 16px;
        cursor: pointer;
      }

      /* Existing styles for the top navigation bar */
      .topnav {
        overflow: hidden;
        background-color: #333;
        z-index: 1000;
      }

      .topnav a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
        font-family: 'Abel', sans-serif;
      }

      .topnav a:hover {
        background-color: #ddd;
        color: black;
      }

      .topnav .icon {
        display: none;
      }
      /* Add animation to the responsive topnav */
      .topnav.responsive {
        position: relative;
        animation: slideDown 0.5s ease forwards;
      }

      /* Add animation to close the responsive topnav */
      .topnav.closing {
        animation: slideUp 0.5s ease forwards;
      }

      /* Define the slideDown animation */
      @keyframes slideDown {
        0% {
          top: -100px; /* Start from above the screen */
        }
        100% {
          top: 0; /* End at the top of the screen */
        }
      }

      /* Media query for screens with a maximum width of 600px */
      @media screen and (max-width: 650px) {
        .topnav:not(.responsive) a:not(.icon) {
          display: none;
        }
        .topnav:not(.responsive) .icon {
          float: left;
          display: block;
          margin-left: 16px; /* Add margin to push it to the top left */
        }

        .topnav.responsive {
          position: relative;
        }

        .topnav.responsive .icon {
          position: absolute;
          left: 10px; /* Adjust the left position as needed */
          top: 0;
          width: 40px;
        }

        .topnav.responsive a {
          float: none;
          display: block;
          text-align: center; /* Center the text horizontally */
          padding: 14px 0; /* Add padding to center the text vertically */
        }
      }

      /* Styles for the search form */
      .search-form {
        float: right;
        margin-top: 14px;
        margin-right: 16px;
      }

      .search-form input[type='text'] {
        padding: 6px;
        border: none;
        border-radius: 4px;
      }

      .search-form input[type='submit'] {
        padding: 6px 10px;
        background-color: #4caf50;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <!-- Navigation bar -->
    <nav class="topnav" id="myTopnav">
      <a href="{% url 'recipes:home' %}">Home</a>
      <a href="{% url 'recipes:list' %}">Recipes</a>
      <a href="{% url 'recipes:add-recipe' %}">Add Recipe</a>
      <a href="{% url 'recipes:about-me' %}">About</a>
      <a href="{% url 'recipes:login' %}">Logout</a>
      <form
        action="{% url 'recipes:search' %}"
        method="GET"
        class="search-form"
        id="search-form"
      >
        {% csrf_token %}
        <input
          type="text"
          name="query"
          placeholder="Search recipe"
          value="{{ query }}"
        />
        <button type="submit">Search</button>
      </form>

      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        &#9776;
      </a>
    </nav>

    <div class="row">
      <div class="column">
        <h2><a href="{% url 'recipes:breakfasts' %}">Breakfasts</a></h2>
        <a href="{% url 'recipes:breakfasts' %}"
          ><img src="{% static 'french_toast_img.jpg' %}" alt="Breakfast"
        /></a>
      </div>
      <div class="column">
        <h2><a href="{% url 'recipes:lunches' %}">Lunches</a></h2>
        <a href="{% url 'recipes:lunches' %}"
          ><img src="{% static 'rice_img.jpg' %}" alt="Lunch"
        /></a>
      </div>
      <div class="column">
        <h2><a href="{% url 'recipes:dinners' %}">Dinners</a></h2>
        <a href="{% url 'recipes:dinners' %}"
          ><img src="{% static 'spaghetti_img.jpg' %}" alt="Dinner"
        /></a>
      </div>
    </div>
    <script>
      // Function to toggle the visibility of navigation links
      function myFunction() {
        var x = document.getElementById('myTopnav');
        if (x.className === 'topnav') {
          x.className += ' responsive';
        } else {
          x.className = 'topnav closing'; // Add the 'closing' class to trigger the closing animation
        }
      }

      // JavaScript to toggle the responsive class and trigger the animation
      function myFunction() {
        var x = document.getElementById('myTopnav');
        var searchBar = document.getElementById('search-form');

        if (x.className === 'topnav') {
          x.className += ' responsive';
          searchBar.style.display = 'none'; // Hide the search bar
        } else {
          x.className = 'topnav';
          searchBar.style.display = 'block'; // Show the search bar
        }
      }
    </script>
  </body>
</html>